# Generated by Django 3.1.6 on 2021-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhaleProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='diet',
            field=models.CharField(default='Krill', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specie',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specie',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
