# Generated by Django 3.1.6 on 2021-04-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhaleProfiles', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
